# Generated by Django 5.1 on 2024-10-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outorgante_object_id', models.PositiveIntegerField()),
                ('outorgado_object_id', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('data_validade', models.DateField()),
                ('escopo', models.CharField(help_text="Escopo da procuração, por exemplo, 'Locação de imóvel'.", max_length=255)),
                ('documento', models.FileField(help_text='Upload do documento da procuração em PDF.', upload_to='procuracoes/')),
                ('outorgado_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outorgado_content_type', to='contenttypes.contenttype')),
                ('outorgante_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outorgante_content_type', to='contenttypes.contenttype')),
            ],
        ),
    ]
