# Generated by Django 5.1 on 2024-08-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_validade', models.DateField()),
                ('escopo', models.CharField(help_text="Escopo da procuração, por exemplo, 'Locação de imóvel'.", max_length=255)),
                ('documento', models.FileField(help_text='Upload do documento da procuração em PDF.', upload_to='procuracoes/')),
                ('outorgante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procuracoes', to='proprietario.proprietario')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procuracoes_representante', to='proprietario.representante')),
            ],
        ),
    ]
