# Generated by Django 5.1 on 2024-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('frio', 'Frio'), ('morno', 'Morno'), ('quente', 'Quente')], default='frio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='etapa_kanban',
            field=models.CharField(choices=[('novo', 'Novo'), ('visita_imovel', 'Visita Imóvel'), ('documentacao', 'Documentação'), ('analise_credito', 'Análise de Crédito'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('contrato_assinado', 'Contrato Assinado')], default='novo', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoEtapaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(max_length=50)),
                ('etapa_atual', models.CharField(max_length=50)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricoStatus',
        ),
    ]
