# Generated by Django 5.1 on 2025-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='numero_casa',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='numero_casa',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
