# Generated by Django 5.1 on 2025-02-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoafisica_rua_casa_pessoajuridica_rua_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='telefone',
        ),
    ]
