# Generated by Django 5.1 on 2025-02-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_remove_pessoafisica_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='rua_casa',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='rua_casa',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
            ],
        ),
    ]
