# Generated by Django 5.1 on 2024-11-19 13:26

import django.db.models.deletion
import django.utils.timezone
import imovel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('endereco', models.CharField(default='', max_length=255)),
                ('bairro', models.CharField(default='', max_length=100)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=50)),
                ('area_total', models.DecimalField(decimal_places=2, default=0, help_text='Área total em metros quadrados', max_digits=7)),
                ('area_util', models.DecimalField(decimal_places=2, default=0, help_text='Área útil em metros quadrados', max_digits=7)),
                ('tipo_imovel', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('comercial', 'Sala Comercial'), ('terreno', 'Terreno'), ('chacara', 'Chácara'), ('sobrado', 'Sobrado'), ('bangalo', 'Bangalô'), ('edicula', 'Edícula'), ('loft', 'Loft'), ('flat', 'Flat'), ('studio', 'Studio')], default=('casa', 'Casa'), max_length=20)),
                ('num_quartos', models.IntegerField(default=0)),
                ('num_banheiros', models.IntegerField(default=0)),
                ('num_vagas_garagem', models.IntegerField(default=0)),
                ('ano_construcao', models.IntegerField(blank=True, null=True)),
                ('caracteristicas_adicionais', models.TextField(blank=True, help_text='Ex: Piscina, churrasqueira, varanda', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível'), ('em_construcao', 'Em Construção'), ('vendido', 'Vendido')], default='disponivel', max_length=20)),
                ('tipo_construcao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], default='novo', max_length=5)),
                ('numero_registro', models.CharField(default='', help_text='Número de matrícula no cartório de imóveis', max_length=50, unique=True)),
                ('disponibilidade', models.BooleanField(default=True, help_text='Indica se o imóvel está disponível')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('cep', models.CharField(default='', max_length=10, validators=[imovel.models.Imovel.validate_cep])),
            ],
            options={
                'indexes': [models.Index(fields=['nome'], name='imovel_imov_nome_904ea0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('permuta', 'Permuta'), ('arrendamento', 'Arrendamento'), ('financiamento', 'Financiamento Imobiliário'), ('leasing', 'Leasing Habitacional')], max_length=13)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('regular', 'Imóvel Regular'), ('iptu_atrasado', 'IPTU Atrasado'), ('taxa_servico_pendente', 'Taxas de Serviço Pendentes'), ('cnd_disponivel', 'Certidão Negativa de Débitos'), ('cpen_disponivel', 'Certidão Positiva com Efeito de Negativa'), ('condominio_pendente', 'Débitos de Condomínio'), ('itbi_pendente', 'ITBI Pendentes')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_fiscais', to='imovel.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, help_text='Comissão em %', max_digits=6, null=True)),
                ('tipo_transacao', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('permuta', 'Permuta'), ('arrendamento', 'Arrendamento'), ('financiamento', 'Financiamento Imobiliário'), ('leasing', 'Leasing Habitacional')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicoes_pagamento', models.TextField(blank=True, help_text='Detalhes sobre financiamento, entrada, parcelamento', null=True)),
                ('data_disponibilidade', models.DateField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='imovel.imovel')),
            ],
        ),
    ]
