# Generated by Django 5.1 on 2024-09-04 12:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='ano_construcao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Área total em metros quadrados', max_digits=7),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_util',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Área útil em metros quadrados', max_digits=7),
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imovel',
            name='caracteristicas_adicionais',
            field=models.TextField(blank=True, help_text='Ex: Piscina, churrasqueira, varanda', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='imovel',
            name='certidoes_licencas',
            field=models.TextField(blank=True, help_text='Certidões e licenças associadas ao imóvel', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='imovel',
            name='disponibilidade',
            field=models.BooleanField(default=True, help_text='Indica se o imóvel está disponível'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imovel',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_banheiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_quartos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='num_vagas_garagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_registro',
            field=models.CharField(default='', help_text='Número de matrícula no cartório de imóveis', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao_fiscal',
            field=models.TextField(blank=True, help_text='Situação dos impostos e tributos', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('comercial', 'Sala Comercial'), ('terreno', 'Terreno')], default=('casa', 'Casa'), max_length=20),
        ),
        migrations.CreateModel(
            name='TransacaoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicoes_pagamento', models.TextField(blank=True, help_text='Detalhes sobre financiamento, entrada, parcelamento', null=True)),
                ('data_disponibilidade', models.DateField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='imovel.imovel')),
            ],
        ),
    ]
