# Generated by Django 5.1 on 2024-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Kanban', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do Kanban', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_prazo', models.DateTimeField(blank=True, null=True)),
                ('cor_atual', models.CharField(default='#00FF00', max_length=7)),
                ('dados_adicionais', models.JSONField(blank=True, default=dict, help_text='Campo para dados dinâmicos adicionais')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('meta_dados', models.JSONField(blank=True, default=dict)),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanColumnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
    ]
