# Generated by Django 5.1 on 2024-10-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaContratoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoInicialColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratosFirmadosColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoAnaliseCreditoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InativosColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Kanban', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do Kanban', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_prazo', models.DateTimeField(blank=True, null=True)),
                ('cor_atual', models.CharField(default='#00FF00', max_length=7)),
                ('dados_adicionais', models.TextField(blank=True, help_text='Campo para dados dinâmicos adicionais')),
                ('data_visita', models.DateTimeField(blank=True, help_text='Data e hora da visita agendada', null=True)),
                ('observacoes_visita', models.TextField(blank=True, help_text='Observações sobre a visita', null=True)),
                ('visita_realizada', models.BooleanField(default=False, help_text='Indica se a visita foi realizada')),
                ('visita_reagendada', models.BooleanField(default=False, help_text='Indica se a visita foi reagendada')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, help_text='Valor final da negociação', max_digits=10, null=True)),
                ('tipo_garantia', models.CharField(blank=True, choices=[('fiador', 'Fiador'), ('deposito_caucao', 'Depósito Caução'), ('seguro_fianca', 'Seguro Fiança'), ('titulo_capitalizacao', 'Título de Capitalização'), ('caucao_imovel', 'Caução de Imóvel')], help_text='Tipo de garantia', max_length=50, null=True)),
                ('prazo_vigencia', models.PositiveIntegerField(blank=True, help_text='Prazo de vigência do contrato em meses', null=True)),
                ('metodo_pagamento', models.CharField(blank=True, help_text='Método de pagamento', max_length=100, null=True)),
                ('status_negociacao', models.CharField(choices=[('em_negociacao', 'Em Negociação'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='em_negociacao', help_text='Status da negociação', max_length=20)),
                ('documentos_anexados', models.FileField(blank=True, help_text='Documentos anexados para análise', null=True, upload_to='documentos/')),
                ('status_documentacao', models.CharField(choices=[('pendente', 'Pendente'), ('completa', 'Completa'), ('incompleta', 'Incompleta'), ('vencida', 'Vencida')], default='pendente', help_text='Status da documentação', max_length=20)),
                ('resultado_analise_credito', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_analise', 'Em Análise')], default='em_analise', help_text='Resultado da análise de crédito', max_length=20)),
                ('data_assinatura', models.DateField(blank=True, help_text='Data da assinatura do contrato', null=True)),
                ('contrato_assinado', models.FileField(blank=True, help_text='Anexe o contrato assinado', null=True, upload_to='contratos/')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanbanColumnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_object_id', models.PositiveIntegerField()),
                ('posicao', models.PositiveIntegerField(help_text='Posição da coluna no Kanban')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='NegociacaoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReprovadoColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitaImovelColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.PositiveIntegerField()),
                ('prazo_alerta', models.PositiveIntegerField(default=3)),
                ('cor_inicial', models.CharField(default='#00FF00', max_length=7)),
                ('cor_alerta', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
