# Generated by Django 5.1 on 2024-11-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='coluna',
            field=models.ForeignKey(help_text='Coluna do Kanban à qual este card está associado', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.kanbancolumn'),
        ),
        migrations.AddField(
            model_name='kanbancolumnorder',
            name='coluna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem', to='kanban.kanbancolumn'),
        ),
        migrations.AddField(
            model_name='kanbancolumnorder',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='kanban.kanban'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumnorder',
            unique_together={('kanban', 'coluna')},
        ),
    ]
