# Generated by Django 5.1 on 2024-10-31 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='kanbancolumnorder',
            name='coluna_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='kanbancolumnorder',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='kanban.kanban'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumnorder',
            unique_together={('kanban', 'coluna_content_type', 'coluna_object_id')},
        ),
    ]
