# Generated by Django 5.1 on 2024-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
