# Generated by Django 5.1 on 2024-11-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_kanbancard_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturacontratocolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='contatoinicialcolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='contratosfirmadoscolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='documentacaoanalisecreditocolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='inativoscolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='negociacaocolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='reprovadocolumn',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='visitaimovelcolumn',
            name='posicao',
        ),
    ]
