# Generated by Django 5.1 on 2024-10-31 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('escritura', 'Escritura Pública'), ('matricula', 'Certidão de Matrícula'), ('cnd', 'Certidão Negativa de Débitos'), ('iptu', 'Certidão Negativa de IPTU'), ('condominio', 'Certidão Negativa de Débitos Condominiais'), ('onus_reais', 'Certidão de Ônus Reais'), ('habitese', 'Habite-se'), ('licenca_construcao', 'Licença de Construção'), ('licenca_ambiental', 'Licença Ambiental'), ('alvara_funcionamento', 'Alvará de Funcionamento')], max_length=50)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='imovel.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH'), ('certidao_nascimento', 'Certidão Nascimento'), ('certidao_casamento', 'Certidão Casamento'), ('comprovante_renda', 'Comprovante Renda'), ('imposto_renda', 'Declaração Imposto de Renda'), ('comprovante_residencia', 'Comprovante de Residência')], max_length=50)),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pessoafisica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('CNPJ', 'CNPJ'), ('contrato_social', 'Contrato Social'), ('cert_negativa_deb_tributarios', 'Certidão Negativa de Débitos Tributários'), ('cert_regul_fgts', 'Certidão Regularidade FGTS')], max_length=50)),
                ('pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pessoajuridica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotosVideoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_midia', models.CharField(choices=[('foto_profissional', 'Foto Profissional'), ('foto_drone', 'Foto Aérea com Drone'), ('foto_360', 'Imagem 360º'), ('planta_baixa', 'Imagem de Planta Baixa'), ('foto_ambientada', 'Foto Ambientada'), ('video_tour', 'Vídeo Tour'), ('tour_virtual_360', 'Tour Virtual 360º'), ('video_drone', 'Vídeo com Drone'), ('video_obra', 'Vídeo de Andamento de Obras'), ('depoimento_cliente', 'Depoimento de Cliente')], max_length=50)),
                ('formato', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='Imagem', max_length=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='imovel.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
