# Generated by Django 5.1 on 2024-09-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('matricula', 'Matrícula'), ('cert_negativa_iptu', 'Certidão Negativa IPTU'), ('cert_negativa_condominio', 'Certidão Negativa Condomínio'), ('cert_negativa_deb_trabalhistas', 'Certidão Negativa Débitos Trabalhistas'), ('recibo_itbi', 'Recibo ITBI'), ('habitese', 'Habite-se'), ('escritura_publica', 'Escritura Pública')], max_length=50)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='imovel.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH'), ('certidao_nascimento', 'Certidão Nascimento'), ('certidao_casamento', 'Certidão Casamento'), ('comprovante_renda', 'Comprovante Renda'), ('imposto_renda', 'Declaração Imposto de Renda'), ('comprovante_residencia', 'Comprovante de Residência')], max_length=50)),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pessoafisica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoPessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_documento', models.CharField(choices=[('CNPJ', 'CNPJ'), ('contrato_social', 'Contrato Social'), ('cert_negativa_deb_tributarios', 'Certidão Negativa de Débitos Tributários'), ('cert_regul_fgts', 'Certidão Regularidade FGTS')], max_length=50)),
                ('pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pessoajuridica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
