# Generated by Django 5.1 on 2024-09-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0001_initial'),
        ('imovel', '0003_historicotransacao_situacaofiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoimovel',
            name='tipo_documento',
            field=models.CharField(choices=[('escritura', 'Escritura Pública'), ('matricula', 'Certidão de Matrícula'), ('cnd', 'Certidão Negativa de Débitos'), ('iptu', 'Certidão Negativa de IPTU'), ('condominio', 'Certidão Negativa de Débitos Condominiais'), ('onus_reais', 'Certidão de Ônus Reais'), ('habitese', 'Habite-se'), ('licenca_construcao', 'Licença de Construção'), ('licenca_ambiental', 'Licença Ambiental'), ('alvara_funcionamento', 'Alvará de Funcionamento')], max_length=50),
        ),
        migrations.CreateModel(
            name='FotosVideoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_emissao', models.DateField()),
                ('tipo_midia', models.CharField(choices=[('foto_profissional', 'Foto Profissional'), ('foto_drone', 'Foto Aérea com Drone'), ('foto_360', 'Imagem 360º'), ('planta_baixa', 'Imagem de Planta Baixa'), ('foto_ambientada', 'Foto Ambientada'), ('video_tour', 'Vídeo Tour'), ('tour_virtual_360', 'Tour Virtual 360º'), ('video_drone', 'Vídeo com Drone'), ('video_obra', 'Vídeo de Andamento de Obras'), ('depoimento_cliente', 'Depoimento de Cliente')], max_length=50)),
                ('formato', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='imovel.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
