# Generated by Django 5.1 on 2024-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacao', '0002_alter_documentoimovel_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosvideoimovel',
            name='formato',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='Imagem', max_length=10),
        ),
    ]
